name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run CI check
      run: npm run ci:check

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run API tests
      env:
        JWT_SECRET: g4GeyzuHXVBb
        ARBITRATOR_PUB_KEY: 86f5d11162ab25c88f4af9cc4224161a40a6e029a45beb8459f0f5f5a95f66d8
        ARBITRATOR_PRIV_KEY: 62325754772ad366d149517311d5fe5cbccb4746ef0285c393ff67f0ad62dd87
        ARK_SERVER_URL: https://mutinynet.arkade.sh
      run: npm run test

# TODO: locally they take up to 27s each, on GH they fail with 40s timeout. Investigate.
#  test-api-acceptance:
#    name: API acceptance tests
#    timeout-minutes: 5
#    runs-on: ubuntu-latest
#    needs: check
#    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '24'
#          cache: 'npm'
#      - name: Install dependencies
#        run: npm ci
#      - name: Run Nigiri
#        uses: vulpemventures/nigiri-github-action@v1
#        with:
#          use_liquid: false
#          use_ln: false
#          use_ark: true
#      - name: Run API acceptance tests
#        env:
#          JWT_SECRET: g4GeyzuHXVBb
#          ARBITRATOR_PUB_KEY: 86f5d11162ab25c88f4af9cc4224161a40a6e029a45beb8459f0f5f5a95f66d8
#          ARBITRATOR_PRIV_KEY: 62325754772ad366d149517311d5fe5cbccb4746ef0285c393ff67f0ad62dd87
#          ARK_SERVER_URL: https://mutinynet.arkade.sh
#        run: npm run test:api:acceptance